name: CI

on: [push]

env:
  ACTION_PHP_EXTENSIONS: zip

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Composer install
        uses: php-actions/composer@v6

      - name: PHPUnit
        uses: php-actions/phpunit@v3
        with:
          php_version: 8.2
          configuration: phpunit.xml.dist

      - name: PHPStan
        uses: php-actions/phpstan@v3
        with:
          php_version: 8.2
          path: src/

      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: 8.2
          path: src/
          standard: phpcs.xml.dist
